### ISSUE TITLE
no Audio from iOS device

### ISSUE THREAD

**Issue by LukeStephen** [Teamxrtc/MeetRTC_iOS#10]
Video both ways is working fine.

Audio from Chrome on my PC to iOS is working fine

BUT audio from the iOS to Chrome is not working.

In Chrome it looks there are two audio streams it is getting from iOS, one has no data in it, the other does, but Chrome is trying to play the one with no data in it. (Looks like firefox plays the correct one)

**Comment by LukeStephen** [comment]
Two way audio works between iOS device and Firefox, just not to Google Chrome

**Comment by LukeStephen** [comment]
two way Audio & Video works with Firefox on Android and Desktop

**Comment by LukeStephen** [comment]
Was this fixed before closed?

**Comment by arunkavi** [comment]
Hi,
This issue was fixed in the commit [https://github.com/Teamxrtc/MeetRTC_iOS/commit/e2285ea161caeaca96d2b36359e63ba0b7867488](url)
