### ISSUE TITLE
Can we allow switching from the front facing to the back facing camera?

### ISSUE THREAD

**Issue by LukeStephen** [Teamxrtc/MeetRTC_iOS#12]
This Objective C code looks like it would do the trick

https://forum.openframeworks.cc/t/switching-between-front-and-back-cameras/6879

**Comment by bhatvv** [comment]
Will look into it.... PR is also welcome.

**Comment by bhatvv** [comment]
#14

**Comment by LukeStephen** [comment]
I tested and can confirm it works, thanks!
